placeOrder(orderDetail)
// .then((orderDetail) => preparingOrder(orderDetail))
// .then((orderDetail) => pickupOrder(orderDetail))
// // preparingOrder(orderDetail)
// // pickupOrder(orderDetail)
// // deliverOrder(orderDetail)